version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

    commands:
      - echo "Instalando dbt..."
      - pip install dbt-redshift

  build:
    commands:
      - echo "Iniciando pipeline CI/CD"
      - echo "Projeto dbt localizado em dbt_tp"
      - ls
      - ls dbt_tp

  post_build:
    commands:
      - echo "Build finalizado com sucesso"

artifacts:
  files:
    - '**/*'